### ISSUE TITLE
GodotGLTF

### ISSUE THREAD

**Issue by GeorgeS2019** [dasg34/mixed-reality-extension-godot#1]
https://github.com/dasg34/GodotGLTF

Sorry posting GodotGLTF issue here.

Is it possible to save a scene using GodotGLTF during runtime with a newly AddChild MeshInstance with a dynamically generated ArrayMesh 

I assume using GLTFSerializer to export the scene using code during Runtime.
An example would be great.

**Comment by dasg34** [comment]
There is no GLTFExporter because GodotGLTF was exported because mre-Godot only need to import GLTF at runtime.

As far as i know, there is GLTF exproter in godot3.4.[(link)](https://godotengine.org/article/godot-3-4-is-released#gltf-exporter)

**Comment by GeorgeS2019** [comment]
@dasg34  Thanks for taking time to answer my question. 
Great job for your company effort to share the MixedReality effort. 
It would be great that the community provide more feedback.

@dasg34 You are right, godot3.4 comes NOW with GLTF exporter.

I wonder if I could use GodotGLTF to export the MeshInstance Mesh (which is dynamically generated).

https://godotengine.org/qa/903/how-to-save-a-scene-at-run-time

I try that, for some reason, the save scene does not include the dynamically generated ArrayMesh attached to the MeshInstance.Mesh

Any suggestion??

**Comment by GeorgeS2019** [comment]
@dasg34  I solved it, I need to set owner everything down the children. Thank you

Keep up your good work !!!!
